source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
gem 'uglifier', '>= 1.3.0'
gem 'js_assets', :path => '../../'

group :development do
  gem 'guard'
  gem 'guard-shell'
end
